library(dplyr)
library(Seurat)

library("optparse")
option_list = list(
    make_option(c("--study"), type="character", default="brain_CG",
                help="which dataset to analyze", metavar="character"),
    make_option(c("--p_top_gene"), type="integer", default=2000,
                help="top genes to study", metavar="integer"),
    make_option(c("--p_top_peak"), type="integer", default=20000,
                help="top peaks to study", metavar="integer"), 
    make_option(c("--ct"), type="character", default="Microglia",
                help="which cell type", metavar="character"),
    make_option(c("--n_pairs"), type="integer", default=1000,
                help="number of randomly sampled pairs", metavar="integer"),
    make_option(c("--n_permu"), type="integer", default=100,
                help="number of permutations", metavar="integer"),
    make_option(c("--sampling"), type="character", default="random",
                help = "how to sample random pairs", metavar="character"),
    make_option(c("--permu_within_batch"), type="character", default="FALSE",
                help="whether to perform the experiment to permute peak accessibilities within batch"),
    make_option(c("--permu_peak"), type="character", default="TRUE",
                help="permute peak ")
)
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);
study <- opt$study
p_top_gene <- opt$p_top_gene
p_top_peak <- opt$p_top_peak
ct <- opt$ct
n_pairs <- opt$n_pairs
n_permu <- opt$n_permu
sampling <- opt$sampling
permu_within_batch <- (opt$permu_within_batch == 'TRUE')
permu_peak <- (opt$permu_peak == 'TRUE')
# two directories to save permuted data, for data with and without batch effects
mode <- ifelse(permu_within_batch, 'permutation_batch_effect', 'permutation')

data_dir <- '/projects/chang/scGRN/peak_gene'
pre_dir <- sprintf('../preprocessing/output/%s/%s', study, ct)
output_dir <- sprintf('output/%s/%s/%s', mode, study, ct)

# load data
if(study == 'brain_CG'){
    #obj <- readRDS(sprintf('%s/data/brain/processed_AD_DLPFC_15.rds', data_dir))
    # subset by disease status and cell type
    #control_inds <- (obj$Diagnosis == 'Unaffected')
    #ct_var <- obj$predicted.id
    pn <- 'peaks'
    obj_suffix <- '_control'
    if(permu_within_batch) batch_var_name <- 'id'
}else if(grepl('PBMC', study)){
    #obj <- readRDS('/projects/chang/scGRN/signac/PBMC/output/PBMC_seurat_obj_peaks_by_ct.rds')	
    #control_inds <- rep(T, ncol(obj))
    #ct_var <- obj$predicted.id
    pn <- 'peaks_ct'
    obj_suffix <- ''
    if(permu_within_batch) batch_var_name <- 'dataset'
}

# load data - generated by preprocessing/save_seurat_obj_by_ct.R
ct_obj <- readRDS(sprintf('%s_seurat_obj%s.rds', pre_dir, obj_suffix))

peak_gene_pairs <- sprintf('%s_%i_peak_%i_gene_pairs.txt', pre_dir, p_top_peak, p_top_gene) %>% read.table(header = T)

# -
# select random pairs
# -
fn <- sprintf('%s_RNA_%i_pairs_%s_sampled_pairs.txt', output_dir, n_pairs, sampling)
if(!file.exists(fn)){
    if(sampling == 'geo_mean'){
        # select n_pairs pairs that evenly cover the mean level of genes and peaks
        # with probability inverse proportional to the density of geo_mean
        # we note that such sampling is not representative of the true peak-gene pairs in real data
        peak_gene_pairs$geo_mean <- sqrt(peak_gene_pairs$peak_mean * peak_gene_pairs$gene_mean)
        # density sample gene-peak pairs
        ## reference:  https://github.com/satijalab/sctransform/blob/master/R/vst.R#L280C5-L284C1
        log_gmean_dens <- density(x = log(peak_gene_pairs$geo_mean), bw = 'nrd', adjust = 1)
        sampling_prob <- 1 / (approx(x = log_gmean_dens$x, y = log_gmean_dens$y, xout = log(peak_gene_pairs$geo_mean))$y + .Machine$double.eps)
        set.seed(2341)
        sampled_pairs <- sample(x = 1:nrow(peak_gene_pairs), size = n_pairs, prob = sampling_prob)
    }else if(sampling == 'random'){
        set.seed(2341)
        sampled_pairs <- sample(x = 1:nrow(peak_gene_pairs), size = n_pairs, replace = F)
    }else if(sampling == 'random_disjoint'){
        set.seed(2341)
        all_genes <- unique(peak_gene_pairs$gene)
        # sample n_pairs random genes
        sampled_genes <- sample(x = all_genes, size = n_pairs, replace = F)
        # for each gene, sample one random peak
        sampled_peaks <- sapply(sampled_genes, function(g) sample(peak_gene_pairs$peak[peak_gene_pairs$gene == g], 1))
        sampled_pg <- data.frame(gene = sampled_genes, peak = sampled_peaks)
        peak_gene_pairs$inds <- 1:nrow(peak_gene_pairs)
        sampled_pairs <- merge(sampled_pg, peak_gene_pairs, by = c('gene', 'peak'), sort = F)$inds
    }else if(sampling == 'top_pairs'){
        peak_gene_pairs$geo_mean <- sqrt(peak_gene_pairs$peak_mean * peak_gene_pairs$gene_mean)
        # extract pairs with the highest geometric mean level
        sampled_pairs <- order(peak_gene_pairs$geo_mean, decreasing = T)[1:n_pairs]
    }
    write.table(peak_gene_pairs[sampled_pairs,],fn)
    sampled_peak_gene_pairs <- peak_gene_pairs[sampled_pairs,]
    print(fn)
}else{
    print('load sampled pairs')
    sampled_peak_gene_pairs <- read.table(fn)
}
                                
# -
# permutation
# -

# permute gene expression
source('adjustment_helper.R')
set.seed(2341)
seeds <- sample(1:1000000, n_permu, replace = F)
rna_seq_depths <- colSums(ct_obj[['RNA']]@counts)
sub_counts <-  ct_obj[['RNA']]@counts[sampled_peak_gene_pairs$gene,] %>% as.matrix %>% t

if(permu_within_batch){
    print('permute gene expression within batches')
    fn <- sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu)
    batch_var <- ct_obj[[batch_var_name]][[1]]
    for(i_permu in 1:n_permu){
	print(i_permu)
        permu_counts <- permute_within_batches(sub_counts, rna_seq_depths, batch_var, seeds[i_permu])
        write.table(permu_counts, sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                    quote = F)
    }
    print(fn)
}else{
    print('permute gene expression')
    fn <- sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu) 
    for(i_permu in 1:n_permu){
        permu_counts <- permute_expression(sub_counts, rna_seq_depths, seeds[i_permu])
        write.table(permu_counts, sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                    quote = F)
    }
    print(fn)
}

if(!permu_peak) {
    q()
}

atac_seq_depths <- colSums(ct_obj[[pn]]@counts)
sub_counts <-  ct_obj[[pn]]@counts[sampled_peak_gene_pairs$peak,] %>% as.matrix %>% t

if(permu_within_batch){
    print('permute peak accessibility within batches')
    batch_var <- ct_obj[[batch_var_name]][[1]]
    for(i_permu in 1:n_permu){
    	print(i_permu)
        permu_counts <- permute_within_batches(sub_counts, atac_seq_depths, batch_var, seeds[i_permu])
        fn <- sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu)
        write.table(permu_counts, fn,
                    quote = F)
    }
    print(fn)
}else{
    print('permute peak accesibility')
    for(i_permu in 1:n_permu){
        permu_counts <- permute_expression(sub_counts, atac_seq_depths, seeds[i_permu])
        fn <- sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu)
        write.table(permu_counts, fn,
                    quote = F)
    }
    print(fn)
}
q()
                                
# for dataset with batch effects
# permute normalized gene expressions within batches
# to preserve technical batch effects
if(n_permu > 0){
    # permute normalized gene expressions
    fn <- sprintf('%s_peak_counts_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu)
    if(!file.exists(fn)){
        print('permute peak counts')
        set.seed(2341)
        seeds <- sample(1:1000000, n_permu, replace = F)
        peak_seq_depths <- colSums(ct_obj[[pn]]@counts)
        sub_counts <-  ct_obj[[pn]]@counts[sampled_peak_gene_pairs$peak,] %>% as.matrix %>% t
        if(permu_within_batch) batch_var <- ct_obj[[batch_var_name]][[1]]
        for(i_permu in 1:n_permu){
            if(permu_within_batch){
                permu_counts <- permute_counts_within_batches(sub_counts, batch_var, seeds[i_permu])
            }else{
                permu_counts <- permute_raw_counts(sub_counts, seeds[i_permu])
            }
            write.table(permu_counts, sprintf('%s_peak_counts_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                       quote = F)
        }
        print(fn)
    }else{
        print('file exists:')
        print(fn)
    }

    # if not only permute the peak counts
    if(!permu_peak_counts){
        if(permu_within_batch){
            # permute normalized peaks
            fn <- sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu)
            for(i_permu in 1:n_permu){
                permu_counts <- permute_within_batches(sub_counts, peak_seq_depths, batch_var, seeds[i_permu])
                write.table(permu_counts, sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                           quote = F)
            }
            fn %>% print
        }else{
            # permute gene expression
            fn <- sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu) 
            if(!file.exists(fn)){
                print('permute gene expression')
                rna_seq_depths <- colSums(ct_obj[['RNA']]@counts)
                sub_counts <-  ct_obj[['RNA']]@counts[sampled_peak_gene_pairs$gene,] %>% as.matrix %>% t
                set.seed(2341)
                seeds <- sample(1:1000000, n_permu, replace = F)
                for(i_permu in 1:n_permu){
                    permu_counts <- permute_expression(sub_counts, rna_seq_depths, seeds[i_permu])
                    write.table(permu_counts, sprintf('%s_RNA_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                           quote = F)
                }
                print(fn)
            }
    
            # permute peak accessibility
            fn <- sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, n_permu)
            if(!file.exists(fn)){
                print('permute peak accessibility')
                set.seed(2341)
                seeds <- sample(1:1000000, n_permu, replace = F)
                peak_seq_depths <- colSums(ct_obj[[pn]]@counts)
                sub_counts <-  ct_obj[[pn]]@counts[sampled_peak_gene_pairs$peak,] %>% as.matrix %>% t
                for(i_permu in 1:n_permu){
                    permu_counts <- permute_expression(sub_counts, peak_seq_depths, seeds[i_permu])
                    write.table(permu_counts, sprintf('%s_peak_%i_pairs_%s_sampled_i_permu_%i.txt', output_dir, n_pairs, sampling, i_permu),
                           quote = F)
                }
                fn%>% print
            }
        }
    }
}
