library(dplyr)
library(Seurat)
library(Matrix)
library(SCENT)
source('../method_implementation/SCENT_early_stop.R')
source('simulation_helper.R')
library("optparse")
option_list = list(
    make_option(c("--study"), type="character", default="brain_CG",
                help="which dataset to analyze", metavar="character"),
    make_option(c("--p_top_gene"), type="integer", default=2000,
                help="top genes to study", metavar="integer"),
    make_option(c("--p_top_peak"), type="integer", default=20000,
                help="top peaks to study", metavar="integer"), 
    make_option(c("--ct"), type="character", default="Microglia",
                help="which cell type", metavar="character"),
    make_option(c("--n_pairs"), type="integer", default=1000,
                help="number of randomly sampled pairs", metavar="integer"),
    make_option(c("--n_permu"), type="integer", default=100,
                help="number of permutations", metavar="integer"),
    make_option(c("--i_permu"), type="integer", default=1,
                help="which permutation replicate to run SCENT on", metavar="integer"),
    make_option(c("--n_cores"), type="integer", default=1,
                help="number of cores to run SCENT", metavar="integer"),
    make_option(c("--sampling"), type="character", default="random",
                help = "how to sample random pairs", metavar="character"),
    make_option(c("--mode"), type="character", default="permutation",
                help="what experiment to run", metavar="character"),
    make_option(c("--n_bootstrap"), type="integer", default=500,
                help="number of bootstrap iterations"),
    make_option(c("--adjust_for_batch"), type = "character", default="FALSE",
               help="whether to adjust for batch effects", metavar="character"),
    make_option(c("--permu_peak"), type="character", default="TRUE",
                help="permute peak"),
    make_option(c("--sparse_factor"), type="numeric", default=1,
                help = "simulate peak data to have seq_depth=seq_depth*sparse_factor", metavar="numeric")
    )
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);
study <- opt$study
p_top_gene <- opt$p_top_gene
p_top_peak <- opt$p_top_peak
ct <- opt$ct
n_pairs <- opt$n_pairs
n_permu <- opt$n_permu
i_permu <- opt$i_permu
sampling <- opt$sampling
mode <- opt$mode
n_bootstrap <- opt$n_bootstrap
adjust_for_batch <- (opt$adjust_for_batch == 'TRUE')
permu_peak <- (opt$permu_peak == 'TRUE')
sparse_factor <- opt$sparse_factor
sparse_factor_suffix <- ifelse(sparse_factor == 1, '', sprintf('s*%.1f_', sparse_factor))

print(sampling)
print(ct)
print(mode)
print(n_bootstrap)
print(adjust_for_batch)
print(sparse_factor_suffix)

data_dir <- '/projects/chang/scGRN/peak_gene'
pre_dir <- sprintf('../preprocessing/output/%s/%s', study, ct)
# directory to load permuted data
permu_output_dir <- sprintf('output/%s/%s/%s', 
                            ifelse(mode == 'permutation_batch_effect', 'permutation_batch_effect', 'permutation'),
                            study, ct)
output_dir <- sprintf('output/%s/%s/%s', mode, study, ct)

# load data
if(study == 'brain_CG'){
    ct_var_name <- 'predicted.id'
    pn <- 'peaks'
    obj_suffix <- '_control'
    batch_var_name <- 'id'
}else if(grepl('PBMC', study)){
    ct_var_name <- 'predicted.id'
    pn <- 'peaks_ct'
    obj_suffix <- ''
    batch_var_name <- 'dataset'
}

print(Sys.time())

# load data - generated by preprocessing/save_seurat_obj_by_ct.R
ct_obj <- readRDS(sprintf('%s_seurat_obj%s.rds', pre_dir, obj_suffix))

# load randomly sampled pairs
sampled_pairs <- sprintf('%s_RNA_%i_pairs_%s_sampled_pairs.txt', permu_output_dir, n_pairs, sampling) %>% read.table(header = T)

# load simulated data
dat_list <- load_simulated_data(mode, 'SCENT', i_permu, permu_peak, sparse_factor=sparse_factor)
rna_counts <- dat_list$gene
peak_counts <- dat_list$peak
    
# make a new peak-gene df due to repeated gene names in sampled pairs
sampled_pairs_new <- sampled_pairs[, c('gene', 'peak')]
if(mode == 'permutation') sampled_pairs_new$gene <- rownames(rna_counts)
rownames(rna_counts) <- sampled_pairs_new$gene
rownames(peak_counts) <- sampled_pairs_new$peak
colnames(rna_counts) <- colnames(peak_counts) <- rownames(ct_obj@meta.data)

mdata <- ct_obj@meta.data
mdata$cell <- rownames(mdata)
mdata$log_total_counts <- log(colSums(ct_obj[['RNA']]@counts))

if(adjust_for_batch){
    batch_var <- ct_obj[[batch_var_name]][[1]]
    n_cells <- length(batch_var)
    unique_ids <- unique(batch_var)
    if(study == 'brain_ROSMAP'){
        batch_var <- sapply(batch_var, function(cs) gsub('-', '_', cs))
        unique_ids <- sapply(unique_ids, function(cs) gsub('-', '_', cs))
    }
    U_id <- matrix(0, nrow = n_cells, ncol = length(unique_ids))
    for(j in 1:ncol(U_id)) U_id[which(batch_var == unique_ids[j]),j] <- 1
    colnames(U_id) <- paste0('subj_', unique_ids)
    mdata <- cbind(mdata, U_id[,-1])
    covariates_set <- c("log_total_counts", colnames(U_id)[-1])
    print(tail(colnames(mdata)))
}else{
    covariates_set <- "log_total_counts"
}
print(paste(covariates_set, collapse = '+'))
                             
SCENT_obj <- CreateSCENTObj(rna = rna_counts, atac = peak_counts,
                            meta.data = mdata,
                            peak.info = sampled_pairs_new,#[sampled_pairs_new$gene=='MALAT1',][1:20,],
                            covariates = covariates_set,
                            celltypes = ct_var_name)

fn <- sprintf('%s_SCENT_%s_sampled_%si_permu_%i_results%s%s.rds', output_dir, sampling, 
              sparse_factor_suffix,
              i_permu,
              ifelse(n_bootstrap!=500, sprintf('_n_bootstrap_%i', n_bootstrap),''),
              ifelse(adjust_for_batch, '_batch_as_covar_adjusted', ''))
print(fn)

if(file.exists(fn)){
	print('results have been computed.')
}else{
	print('Start SCENT')
	start <- Sys.time() 
	start %>% print
	SCENT_obj <- SCENT_algorithm_early_stop(object = SCENT_obj, celltype = ct,
                                            ncores = opt$n_cores, regr = 'poisson', bin = TRUE,
                                            early_stop_R = n_bootstrap)
    # too slow
    #SCENT_obj <- SCENT_algorithm(object = SCENT_obj, celltype = ct,
    #                     ncores = 1,
    #                     regr = 'poisson', bin = TRUE)
	end <- Sys.time()
	end %>% print
	print('SCENT ended')
	print(end - start)
    	
	print(SCENT_obj@SCENT.result)
	saveRDS(SCENT_obj@SCENT.result, fn)
}
print(fn)
