library(dplyr)
library(Seurat)
library(Matrix)
source('../method_implementation/moment_regressions.R')
source('simulation_helper.R')
library("optparse")
option_list = list(
    make_option(c("--study"), type="character", default="brain_CG",
              help="which dataset to analyze", metavar="character"),
    make_option(c("--p_top_gene"), type="integer", default=2000,
              help="top genes to study", metavar="integer"),
    make_option(c("--p_top_peak"), type="integer", default=20000,
              help="top peaks to study", metavar="integer"), 
    make_option(c("--ct"), type="character", default="Microglia",
              help="which cell type", metavar="character"),
    make_option(c("--n_pairs"), type="integer", default=1000,
              help="number of randomly sampled pairs", metavar="integer"),
    make_option(c("--n_permu"), type="integer", default=100,
              help="number of permutations", metavar="integer"),
    make_option(c("--sampling"), type="character", default="random",
                help = "how to sample random pairs", metavar="character"),
    make_option(c("--mode"), type="character", default="permutation",
                help="what experiment to run", metavar="character"),
    make_option(c("--adjust_for_batch"), type = "character", default="FALSE",
               help="whether to adjust for batch effects", metavar="character"),
    make_option(c("--permu_peak"), type="character", default="TRUE",
                help="permute peak"),
    make_option(c("--sparse_factor"), type="numeric", default=1,
                help = "simulate peak data to have seq_depth=seq_depth*sparse_factor", metavar="numeric")
)
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);
study <- opt$study
p_top_gene <- opt$p_top_gene
p_top_peak <- opt$p_top_peak
ct <- opt$ct
n_pairs <- opt$n_pairs
n_permu <- opt$n_permu
sampling <- opt$sampling
mode <- opt$mode
adjust_for_batch <- opt$adjust_for_batch == 'TRUE'
batch_suffix <- ifelse(adjust_for_batch, '_batch_adjusted', '')
permu_peak <- (opt$permu_peak == 'TRUE')
sparse_factor <- opt$sparse_factor
sparse_factor_suffix <- ifelse(sparse_factor == 1, '', sprintf('s*%.1f_', sparse_factor))

print(sampling)
print(ct)
print(mode)
print(sparse_factor_suffix)

data_dir <- '/projects/chang/scGRN/peak_gene'
pre_dir <- sprintf('../preprocessing/output/%s/%s', study, ct)
permu_output_dir <- sprintf('output/%s/%s/%s',
                            ifelse(mode == 'permutation_batch_effect', 'permutation_batch_effect', 'permutation'),
                            study, ct)
output_dir <- sprintf('output/%s/%s/%s', mode, study, ct)

# load data
if(study == 'brain_CG'){
    ct_var_name <- 'predicted.id'
    pn <- 'peaks'
    obj_suffix <- '_control'
    if(adjust_for_batch) batch_var_name <- 'id'
}else if(grepl('PBMC', study)){
    ct_var_name <- 'predicted.id'
    pn <- 'peaks_ct'
    obj_suffix <- ''
}

# load data - generated by preprocessing/save_seurat_obj_by_ct.R
ct_obj <- readRDS(sprintf('%s_seurat_obj%s.rds', pre_dir, obj_suffix))


# obtain sequencing depths
rna_seq_depths <- colSums(ct_obj[['RNA']]@counts)
peak_seq_depths <- colSums(ct_obj[[pn]]@counts)


peak_gene_pairs <- sprintf('%s_%i_peak_%i_gene_pairs.txt', pre_dir, p_top_peak, p_top_gene) %>% read.table
sampled_pairs <- sprintf('%s_RNA_%i_pairs_%s_sampled_pairs.txt', permu_output_dir, n_pairs, sampling) %>% read.table

res_list <- list()
if(adjust_for_batch){
    batch_var <- ct_obj[[batch_var_name]] %>% unlist
    unique_batches <- unique(batch_var)
    rna_mu_mat <- peak_mu_mat <- array(dim = c(nrow(sampled_pairs), length(unique_batches), n_permu))
    rna_sigma_sq_mat <- peak_sigma_sq_mat <- matrix(nrow = nrow(sampled_pairs), ncol = n_permu)
}

for(i_permu in 1:n_permu){
    print(i_permu)
    # load simulated data
    dat_list <- load_simulated_data(mode, 'proposed', i_permu, permu_peak, sparse_factor = sparse_factor)
    # regressions for genes
    X_gene <- dat_list$gene
    # regressions for peaks
    X_peaks <- dat_list$peak

    if(grepl('permutation', mode)){
        peak_seq_depths <- colSums(ct_obj[[pn]]@counts) + rowSums(X_peaks) - colSums(ct_obj[[pn]]@counts[sampled_pairs$peak,])
    }

    if(!adjust_for_batch){
        gene_mar_pars <- mom_marginal(X_gene, rna_seq_depths, irls=T)
        peak_mar_pars <- mom_marginal(X_peaks, peak_seq_depths, verbose = T, irls=T)
    }else{
        batch_mat <- matrix(0, nrow = ncol(ct_obj), ncol = length(unique_batches))
        colnames(batch_mat) <- unique_batches
        for(b in unique_batches) batch_mat[batch_var == b, b] <- 1
        gene_mar_pars <- mom_marginal_adj_for_batch(X_gene, rna_seq_depths, batch=batch_mat, irls=T)
        peak_mar_pars <- mom_marginal_adj_for_batch(X_peaks, peak_seq_depths, batch=batch_mat, irls=T)
        rna_mu_mat[,,i_permu] <- gene_mar_pars$mu
        peak_mu_mat[,,i_permu] <- peak_mar_pars$mu
        rna_sigma_sq_mat[,i_permu] <- gene_mar_pars$sigma_sq
        peak_sigma_sq_mat[,i_permu] <- peak_mar_pars$sigma_sq
    }
    
    # estimate correlations
    res_mat <- matrix(nrow = n_pairs, ncol = 2)
    colnames(res_mat) <- c('covar', 'test_stat')
    # for each gene, evaluate its correlation with neighbouring peaks
    for(i_g in 1:nrow(sampled_pairs)){
        covar_res <- mom_covariance(gene_mar_pars$X_centered[,i_g], 
                                    peak_mar_pars$X_centered[,i_g, drop=F],
                                    gene_mar_pars$w[,i_g],
                                    peak_mar_pars$w[,i_g, drop=F],
                                    rna_seq_depths,
                                    peak_seq_depths,
                                    gene_mar_pars$X_var[, i_g],
                                    peak_mar_pars$X_var[, i_g, drop=F])
        res_mat[i_g,] <- c(covar_res$covar, covar_res$test_stat)
    }
    res_list[[i_permu]] <- res_mat
}
if(n_permu > 1){
    fn <- sprintf('%s_proposed_%s_sampled_%sresults%s.rds', output_dir, sampling, sparse_factor_suffix, batch_suffix)
    saveRDS(res_list, fn)
    print(fn)
}else{
    fn <- sprintf('%s_proposed_%s_sampled_i_%spermu_1_results%s.rds', output_dir, sampling, sparse_factor_suffix, batch_suffix)
    saveRDS(res_list, fn)
    print(fn)    
}

if(adjust_for_batch){
    saveRDS(list(rna_mu_mat, peak_mu_mat, rna_sigma_sq_mat, peak_sigma_sq_mat), 
	    sprintf('%s_proposed_%s_sampled_%smarginal_est%s.rds', output_dir, sampling, sparse_factor_suffix, batch_suffix))
}
