# for revision
# add trio results for SCENT and Signac
#
# due to the high computational costs, we filter the candidate peak-TF pairs by those h
# that have significant TF-gene co-expression by CS-CORE, and significant peak-gene by SCENT/Signac

source('reproducibility_helper.R')
library(dplyr)
library(Seurat)
library(Signac)
library(JASPAR2020)
source('trio_analysis_helper.R')

res_list <- list()
ct <- 'CD14 Mono'
study <- 'PBMC_4_combined'
pairs_suffix <- ''

##
# load TF info
##
# load seurat object
pre_dir <- sprintf('../preprocessing/output/%s/%s', study, ct)
output_dir <- sprintf('output/%s/%s', study, ct)
obj_suffix <- ''
# load data - generated by preprocessing/save_seurat_obj_by_ct.R
ct_obj <- readRDS(sprintf('%s_seurat_obj%s.rds', pre_dir, obj_suffix))

# load motif info
if(grepl('PBMC', study)){
    DefaultAssay(ct_obj) <- 'peaks_ct'
    motif.object <- readRDS(sprintf('../preprocessing/output/%s/motif.object.rds', study))
}else if(grepl('brain', study)){
    motif.object <- readRDS('output/brain_CG/motif.object.rds')
}
Motifs(ct_obj) <- motif.object
# extract all TF names from JASPAR 2020 database
full_TF_names <- ConvertMotifID(ct_obj, id = colnames(motif.object@data))

# load all TFs and TF-peak pairs, pre-evaluated in run_proposed.R
TF_peak <- readRDS(sprintf('%s_TF_peak_coexp%s.rds', output_dir, sprintf('%s_batch_adjusted', pairs_suffix)))


##
# load methods' results on peak-gene
##
res_list[['Signac']] <- load_Signac(ct, datasets = 'PBMC_4_combined',
                                    fn_suffix = '_permu_adjusted')[[1]]
res_list[['SCENT']] <- load_SCENT(ct, n_sets=10,
                                  datasets = 'PBMC_4_combined',
                                 '_batch_as_covar_adjusted_n_bootstrap_5000')[[1]]
res_list[['proposed']] <- load_proposed(ct, study, sprintf('%s_batch_adjusted', pairs_suffix))[[1]]

##
# load TF-gene results from CS-CORE
##

# use co-expression results from CS-CORE
TF_coexp <- readRDS(sprintf('%s_TF_gene_coexp%s.rds', sprintf('output/%s/%s', study, ct),
                       sprintf('%s_batch_adjusted', pairs_suffix)))
TF_target_p <- TF_coexp$pval


pair_sigp_cutoff <- 0.001


TF_peak_sub_list <- list()
for(method in c('Signac', 'SCENT')){
    tmp <- list()
    for(TF in names(TF_peak)){
        results <- res_list[[method]]
        peaks_w_binding_motifs <- names(which(motif.object@data[,full_TF_names == TF] != 0))
        results_peaks_w_motif_inds <- results$peak %in% peaks_w_binding_motifs
        # from peak to gene
        peak_gene_pval <- results$pval[results_peaks_w_motif_inds]
        # from gene to TF
        gene_TF_pval <- TF_target_p[TF, results$gene][results_peaks_w_motif_inds]
        trio_inds <- which((peak_gene_pval < pair_sigp_cutoff) & (gene_TF_pval < pair_sigp_cutoff))
        tmp[[TF]] <- unique(results$peak[results_peaks_w_motif_inds][trio_inds]) # there exists single enhancer that regulates multiple genes
    }
    TF_peak_sub_list[[method]] <- tmp
}

saveRDS(TF_peak_sub_list, 'output/PBMC_4_combined/trio_peak_TF_pairs.rds')