library(dplyr)
library(Seurat)
library(Matrix)
library(SCENT)
source('../method_implementation/SCENT_early_stop.R')
library("optparse")
option_list = list(
    make_option(c("--study"), type="character", default="brain_CG",
              help="which dataset to analyze", metavar="character"),
    make_option(c("--p_top_gene"), type="integer", default=2000,
              help="top genes to study", metavar="integer"),
    make_option(c("--p_top_peak"), type="integer", default=20000,
              help="top peaks to study", metavar="integer"), 
    make_option(c("--ct"), type="character", default="Microglia",
              help="which cell type", metavar="character"),
    make_option(c("--n_cores"), type="integer", default=1,
              help="number of cores to run SCENT", metavar="integer"),
    make_option(c("--i_set"), type="integer", default=1,
                help = "which subset to run", metavar="integer"),
    make_option(c("--n_sets"), type="integer", default=50,
                help = "total number of subsets", metavar="integer"),
    make_option(c("--cell_subset"), type="character", default="Control",
                help="which subset of cells to analyze", metavar="character"),
    make_option(c("--i_permu"), type="integer", default=1,
              help="which permutation replicate", metavar="integer"),
    make_option(c("--adjust_for_batch"), type = "character", default="FALSE",
               help="whether to adjust for batch effects", metavar="character"),
    make_option(c("--n_bootstrap"), type="integer", default=500,
                help="how many bootstrap iterations to run in SCENT",
                metavar="integer"),
    make_option(c("--run_TF_peak"), type="character", default="FALSE",
                help="whether to run TF peak association")
    )
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);
study <- opt$study
p_top_gene <- opt$p_top_gene
p_top_peak <- opt$p_top_peak
ct <- opt$ct
i_set <- opt$i_set
n_sets <- opt$n_sets
cell_subset <- opt$cell_subset
run_TF_peak <- (opt$run_TF_peak == 'TRUE')
print(cell_subset)
i_permu <- opt$i_permu

# -
# various types of suffix for documenting the analysis setting
# -
fn_suffix <- ifelse(cell_subset == 'Control', '', '_All_cells')
if(p_top_gene != 2000){
    fn_suffix <- paste0(fn_suffix, sprintf('_p_top_%i_%i', p_top_gene, p_top_peak))
}
adjust_for_batch <- (opt$adjust_for_batch == 'TRUE')
n_bootstrap <- opt$n_bootstrap
adjust_suffix <- ifelse(adjust_for_batch, '_batch_as_covar_adjusted', '')


fn_suffix <- sprintf('%s%s', fn_suffix, adjust_suffix)
if(n_bootstrap != 500) fn_suffix <- sprintf('%s_n_bootstrap_%i', fn_suffix, n_bootstrap)

print(fn_suffix)
print(sprintf('%s cores', opt$n_cores))
print(ct)
print(i_set)
print(n_sets)
print(i_permu)

pre_dir <- sprintf('../preprocessing/output/%s/%s', study, ct)
output_dir <- sprintf('output/%s/%s', study, ct)


peak_TF_suffix <- ifelse(run_TF_peak, '_TF_peak', '')
if(n_sets != 50){
        fn <- sprintf('%s_SCENT_n_sets_%i_i_set_%i_results%s%s.rds', output_dir, n_sets, i_set, fn_suffix, peak_TF_suffix)
}else{
        fn <- sprintf('%s_SCENT_i_set_%i_results%s%s.rds', output_dir, i_set, fn_suffix, peak_TF_suffix)
}
print(fn)

if(file.exists(fn)){
    print(fn)
    print('results have been computed')	
    #q()
}

# -
# load data - generated by ../preprocessing/save_seurat_obj_by_ct.R
# -
if(grepl('brain', study)){
    if(study == 'brain_CG'){
        cts <- c('Microglia', 'Excitatory', 'Inhibitory', 'Oligodendrocytes', 'Astrocytes')
        ct_var_name <- 'predicted.id'
        if(adjust_for_batch) batch_var_name <- 'id'
    }else if(study == 'brain_ROSMAP'){
        cts <- c('Mic', 'Exc', 'Inh', 'Oli', 'Ast')
        ct_var_name <- 'MajorCellType'
        if(adjust_for_batch) batch_var_name <- 'Sample'
    }
    if(cell_subset == 'Control'){
        obj_suffix <- '_control'
    }else if(cell_subset == 'All'){
        obj_suffix <- ''
    }
    pn <- 'peaks'
}else if(grepl('PBMC', study)){
    ct_var_name <- 'predicted.id'
    pn <- 'peaks_ct'
    obj_suffix <- ''
    if(adjust_for_batch) batch_var_name <- 'dataset'
}
ct_obj <- readRDS(sprintf('%s_seurat_obj%s.rds', pre_dir, obj_suffix))

print('data loaded')

# get peak gene pairs
if(!run_TF_peak){
    peak_gene_pairs <- sprintf('%s_%i_peak_%i_gene_pairs.txt', pre_dir, p_top_peak, p_top_gene) %>% read.table(header = T)
}else if(run_TF_peak & study == 'PBMC_4_combined' & ct == 'CD14 Mono'){
    # load TF-peak pairs precompted with get_trio_peak_TF_pairs.R
    TF_peak_pairs <- readRDS('output/PBMC_4_combined/trio_peak_TF_pairs.rds')[['SCENT']]
    for(k in 1:length(TF_peak_pairs)){
        if(length(TF_peak_pairs[[k]]) >= 1){
            TF_peak_pairs[[k]] <- data.frame(peak = TF_peak_pairs[[k]], gene = names(TF_peak_pairs)[k])
        }
    }
    peak_gene_pairs <- do.call(rbind, TF_peak_pairs)
}
top_genes <- read.table(sprintf('%s_top_%i_genes.txt', pre_dir, p_top_gene))[[1]]
top_peaks <- read.table(sprintf('%s_top_%i_peaks.txt', pre_dir, p_top_peak))[[1]]

print(sprintf('evaluate %i pairs', nrow(peak_gene_pairs)))
print(dim(peak_gene_pairs))

n_pairs_per_set <- floor(nrow(peak_gene_pairs) / n_sets)
i_set_pair_inds <- ((i_set - 1) * n_pairs_per_set + 1) : (i_set * n_pairs_per_set)
if(i_set == n_sets) i_set_pair_inds <- ((i_set - 1) * n_pairs_per_set + 1) : nrow(peak_gene_pairs)
print(min(i_set_pair_inds))
print(max(i_set_pair_inds))

# -
# run SCENT
# -
# extract counts
peak_counts <- ct_obj[[pn]]@counts[unique(peak_gene_pairs$peak),]
rna_counts <- ct_obj[['RNA']]@counts[unique(peak_gene_pairs$gene),]
print(dim(peak_counts))
print(dim(rna_counts))

# set covariates
mdata <- ct_obj@meta.data
mdata$cell <- rownames(mdata)
mdata$log_total_counts <- log(colSums(ct_obj[['RNA']]@counts))

if(adjust_for_batch){
    batch_var <- ct_obj[[batch_var_name]][[1]]
    n_cells <- length(batch_var)
    unique_ids <- unique(batch_var)
    if(study == 'brain_ROSMAP'){
        batch_var <- sapply(batch_var, function(cs) gsub('-', '_', cs))
        unique_ids <- sapply(unique_ids, function(cs) gsub('-', '_', cs))
    }
    U_id <- matrix(0, nrow = n_cells, ncol = length(unique_ids))
    for(j in 1:ncol(U_id)) U_id[which(batch_var == unique_ids[j]),j] <- 1
    colnames(U_id) <- paste0('subj_', unique_ids)
    mdata <- cbind(mdata, U_id[,-1])
    covariates_set <- c("log_total_counts", colnames(U_id)[-1])
    print(tail(colnames(mdata)))
}else{
    covariates_set <- "log_total_counts"
}
print(paste(covariates_set, collapse = '+'))
print(length(i_set_pair_inds))

SCENT_obj <- CreateSCENTObj(rna = rna_counts, atac = peak_counts,
                            meta.data = mdata,
			    peak.info = peak_gene_pairs[i_set_pair_inds, c('gene', 'peak')],
                            covariates = covariates_set,
                            celltypes = ct_var_name)
print('Start SCENT')
start <- Sys.time() 
start %>% print

print(dim(peak_gene_pairs))
if(n_bootstrap <= 5000){
	print(sprintf('Run SCENT with %i bootstrap iterations.', n_bootstrap))
    SCENT_obj <- SCENT_algorithm_early_stop(object = SCENT_obj, celltype = ct,
                                            ncores = opt$n_cores, regr = 'poisson', bin = TRUE,
                                            early_stop_R = n_bootstrap)
}else{
	print(sprintf('n_bootstrap=%i', n_bootstrap))
	print('Run original SCENT (can be extremely slow)')
	print(Sys.time())
    SCENT_obj <- SCENT_algorithm(object = SCENT_obj, celltype = ct,
                                 ncores = 1,
                                 regr = "poisson",
                                 bin = TRUE)
	print(Sys.time())
}

end <- Sys.time()
end %>% print
print('SCENT ended')
print(end - start)

print(SCENT_obj@SCENT.result %>% head)
print(SCENT_obj@SCENT.result %>% tail)
saveRDS(SCENT_obj@SCENT.result, fn)
print(fn)
    
